[package]
name = "pipewire-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
pipewire = "0.8"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
regex = "1.10"
log = "0.4"
env_logger = "0.10"
lazy_static = "1.4"
