name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Build Client
      working-directory: ./wayland-osd-client
      run: cargo build --verbose
    - name: Install dependencies for Server
      run: sudo apt update && sudo apt-get install -y libglib2.0-dev libpango1.0-dev libgdk-pixbuf-2.0-dev libgtk-4-dev libgtk4-layer-shell-dev
    - name: Build Server
      working-directory: ./wayland-osd-server
      run: cargo build --verbose
